//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 06:16:05 PM BST 
//


package pt.uc.dei.aor.paj.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}titulo"/>
 *         &lt;element ref="{}data"/>
 *         &lt;element ref="{}autor"/>
 *         &lt;element ref="{}corpo"/>
 *         &lt;element ref="{}urlPagina"/>
 *         &lt;element ref="{}descricao"/>
 *         &lt;element ref="{}imagem"/>
 *         &lt;element ref="{}video"/>
 *         &lt;element ref="{}categoria"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titulo",
    "data",
    "autor",
    "corpo",
    "urlPagina",
    "descricao",
    "imagem",
    "video",
    "categoria"
})
@XmlRootElement(name = "noticia")
public class Noticia {

    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String data;
    @XmlElement(required = true)
    protected String autor;
    @XmlElement(required = true)
    protected String corpo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String urlPagina;
    @XmlElement(required = true)
    protected String descricao;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String imagem;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String video;
    @XmlElement(required = true)
    protected String categoria;

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutor(String value) {
        this.autor = value;
    }

    /**
     * Gets the value of the corpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorpo() {
        return corpo;
    }

    /**
     * Sets the value of the corpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorpo(String value) {
        this.corpo = value;
    }

    /**
     * Gets the value of the urlPagina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlPagina() {
        return urlPagina;
    }

    /**
     * Sets the value of the urlPagina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlPagina(String value) {
        this.urlPagina = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the imagem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagem() {
        return imagem;
    }

    /**
     * Sets the value of the imagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagem(String value) {
        this.imagem = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVideo(String value) {
        this.video = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    @Override
    public String toString() {
    	return "Autor: " + this.autor + "\nCorpo: " + this.corpo + "\nData: " + this.data + "\nTitulo: " + 
    			this.titulo + "\nUrl: " + this.urlPagina +  "\nCategoria: " + this.categoria + "\nDescrição: "  
    			+ this.descricao + "\nVideo: " + this.video +  "\nImagem: " + this.imagem 
    			+ "\n----------------------------------------";
    }

}
