//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 06:16:05 PM BST 
//


package pt.uc.dei.aor.paj.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.uc.dei.aor.paj.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Corpo_QNAME = new QName("", "corpo");
    private final static QName _Data_QNAME = new QName("", "data");
    private final static QName _Categoria_QNAME = new QName("", "categoria");
    private final static QName _Imagem_QNAME = new QName("", "imagem");
    private final static QName _Titulo_QNAME = new QName("", "titulo");
    private final static QName _Video_QNAME = new QName("", "video");
    private final static QName _UrlPagina_QNAME = new QName("", "urlPagina");
    private final static QName _Autor_QNAME = new QName("", "autor");
    private final static QName _Descricao_QNAME = new QName("", "descricao");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.uc.dei.aor.paj.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Noticias }
     * 
     */
    public Noticias createNoticias() {
        return new Noticias();
    }

    /**
     * Create an instance of {@link Noticia }
     * 
     */
    public Noticia createNoticia() {
        return new Noticia();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "corpo")
    public JAXBElement<String> createCorpo(String value) {
        return new JAXBElement<String>(_Corpo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data")
    public JAXBElement<String> createData(String value) {
        return new JAXBElement<String>(_Data_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "categoria")
    public JAXBElement<String> createCategoria(String value) {
        return new JAXBElement<String>(_Categoria_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imagem")
    public JAXBElement<String> createImagem(String value) {
        return new JAXBElement<String>(_Imagem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "titulo")
    public JAXBElement<String> createTitulo(String value) {
        return new JAXBElement<String>(_Titulo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "video")
    public JAXBElement<String> createVideo(String value) {
        return new JAXBElement<String>(_Video_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "urlPagina")
    public JAXBElement<String> createUrlPagina(String value) {
        return new JAXBElement<String>(_UrlPagina_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autor")
    public JAXBElement<String> createAutor(String value) {
        return new JAXBElement<String>(_Autor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "descricao")
    public JAXBElement<String> createDescricao(String value) {
        return new JAXBElement<String>(_Descricao_QNAME, String.class, null, value);
    }

}
